# Pins used in the PLD file.
# Pin 1 will be mapped to CLK, pin 12 to GND, pin 24 to VCC
[pins]
A20=4
A21=5
A22=6
A23=7
LDS=8
AS=9
UDS=10
RWB=11
OVR=13
UART=14
IREG=15
RAMLO=16
ROM=17
OE=18
WR=19
AREG=20
TIMERACK=21
RAMHI=22
EXTPORT=23

[addresspins]
# Key: Name of address space
# Value: Commaseparated list of pins (MSB,..,LSB) to form address space
ADDR4=A23,A23,A22,A21
ADDR1=A23

[decode]
# Key: Name of address space
# Value: bitmask:value Bitmask as defined under [addresspins], value the mask value
RAM=      ADDR4:0x0
ROML=     ADDR4:0x0
TIMERACK= ADDR4:0xa
UART=     ADDR4:0xb
EXT=      ADDR4:0xc
OREG=     ADDR4:0xd
IREG=     ADDR4:0xe
ROMH=     ADDR4:0xf

