# Pins used in the PLD file.
# Pin 1 will be mapped to CLK, pin 12 to GND, pin 24 to VCC
[pins]
A20=4
A21=5
A22=6
A23=7
LDS=8
AS=9
UDS=10
RWB=11
OVR=13
UART=14
IREG=15
RAMLO=16
ROM=17
OE=18
WR=19
AREG=20
TIMERACK=21
RAMHI=22
EXTPORT=23

[addresspins]
# Key: Name of address space
# Value: Commaseparated list of pins (MSB,..,LSB) to form address space
ADDR4=A23,A22,A21,A20
ADDR1=A23

[addresses]
# Key: Name of address space
# Value: bitmask:value Bitmask as defined under [addresspins], value the mask value
RAM=      ADDR4:0x0
TIMERACK= ADDR4:0xa
UART=     ADDR4:0xb
EXT=      ADDR4:0xc
OREG=     ADDR4:0xd
IREG=     ADDR4:0xe
ROM=     ADDR4:0xf

[macros]
# Create macros that will be expanded in the [decode] section
# Use {ADDRESS} to expand an address defined in the [addresses] section
IS_READ=/AS * RWB
IS_WRITE=/AS * /RWB
ROM_OVL=/OVR * {RAM}
RAM_READ=/AS * OVR * {RAM}
RAM_WRITE={IS_WRITE} * {RAM}
BYTE_ACCESS=/AS * /LDS
BYTE_WRITE={IS_WRITE} * /LDS
BYTE_READ={IS_READ} * /LDS

[decode]
# Use {MACRO} to expand a MACRO
OE={IS_READ}
WR={IS_WRITE}

# ROM outputs both bytes regardless of access when a read is issue
/ROM={IS_READ} * {ROM_OVL} + {IS_READ} * {ROM}

/RAMLO={RAM_READ} * /LDS + {RAM_WRITE} * /LDS
/RAMHI={RAM_READ} * /UDS + {RAM_WRITE} * /UDS

# Timer ack can be any access
/TIMERACK={TIMERACK} * /AS

/UART={UART} * {BYTE_ACCESS}
/EXTPORT={EXT} * {BYTE_WRITE}

# Add the rest
